Extending EPB documentation added.
o3de/sig-testing pull request #3
Opened 2021-07-08 19:16 UTC by AMZN-scspaldi

Signed-off-by: scspaldi <scspaldi@amazon.com>

2021-07-08 21:27 UTC, evanchia-ly-sdets requested changes

2021-07-08 21:27 UTC, evanchia-ly-sdets commented on editorpythonbindings.md
> +EditorPythonBindings (EPB) offers access to build scalable multi-point, scriptable, end-to-end, round-trip pipelines, and common framework solutions for game content creators and Open 3D engine (O3DE
I think "engine" should be capitalized

2021-07-08 21:27 UTC, evanchia-ly-sdets commented on editorpythonbindings.md
> +This code snippet the entry point into the entire object/widget hierarchy of our Qt application.  From here, you can do things like access the menu bars/toolbars, find children widgets to inspect/inj
Missing word at start of sentence

2021-07-08 21:27 UTC, evanchia-ly-sdets commented on editorpythonbindings.md
> +import Tests.ly_shared.pyside_utils as pyside_utils
Have we moved this module to the editor test tools package?

2021-07-08 21:27 UTC, evanchia-ly-sdets commented on editorpythonbindings.md
> +The EPB gem is an optional gem. This means that when a project (e.g. Starter Game or Samples Project) wants to expose scriptable functionality to Python, a project team needs to enable the “Editor Py
Do we still have StarterGame and SamplesProject? I thought those were deprecated.

2021-07-14 18:27 UTC, jackalbe commented on editorpythonbindings.md
> +The default Scope value is AZ::Script::Attributes::ScopeFlags::Launcher  since the scripting contexts for Lua and Scripting Canvas where the first mechanisms for binding behavior.
The AZ::Script::Attributes::ScopeFlags::Common and AZ::Script::Attributes::ScopeFlags::Automation flags should also be mentioned

2021-07-14 18:31 UTC, jackalbe commented on editorpythonbindings.md
> +This code snippet is the entry point into the entire object/widget hierarchy of our Qt application.  From here, you can do things like access the menu bars/toolbars, find children widgets to inspect/
The "QtForPython" gem is also required for Qt PySide2 stuff.

2021-07-16 18:04 UTC, evanchia-ly-sdets requested changes

2021-07-16 20:09 UTC, evanchia-ly-sdets commented on editorpythonbindings.md
> +<!-- TODO: Include link to O3DE EPB documentation -->
Just a reminder for this TODO

2021-07-16 20:09 UTC, evanchia-ly-sdets approved these changes

2021-07-26 17:47 UTC, jackalbe approved these changes

2021-07-26 17:50 UTC, merged